services:
  php-apache:
    build: .
    volumes:
      - "./:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/30-custom.ini"
    ports:
      - "80:80"
      - "443:443" # for SSL
    environment:
      - ALLOW_OVERRIDE=true
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./docs/db_dev.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
